version: '3'
services:
  flask:
    build: .
    command: gunicorn -b 0.0.0.0:5001 hello:app --reload
    environment:
      - FLASK_APP=hello.py
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=True
    ports:
      - "5001:5001"
    volumes:
      - ./:/app